/**
 * @name Codebase File Classification Analysis
 * @description Analyzes and categorizes source code files by identifying
 *              auto-generated content and test files through pattern matching
 *              and contextual location analysis within the codebase structure.
 *              This classification helps in understanding code organization
 *              and filtering specific file types during security analysis.
 * @kind file-classifier
 * @id py/file-classifier
 */

// Import Python module for comprehensive Python code analysis capabilities
import python
// Import GeneratedCode filter module to detect automatically generated source files
import semmle.python.filters.GeneratedCode
// Import Tests filter module for identifying test-related files and directories
import semmle.python.filters.Tests

// Primary classification query that categorizes files based on their origin and purpose
from File targetFile, string fileCategory
where 
  // First classification criteria: Files that are auto-generated by tools or processes
  (targetFile instanceof GeneratedFile and fileCategory = "generated")
  // Second classification criteria: Files residing within test directories or contexts
  or
  (exists(TestScope testLocation | testLocation.getLocation().getFile() = targetFile) and fileCategory = "test")
select targetFile, fileCategory