import python
import semmle.code.cpp.dataflow.DataFlow
import semmle.code.cpp.security.CommandInjection

from CallExpr call, Argument arg, StringLiteral str
where call.getMethod().getName() = "system" and
      arg.getArgumentPosition() = 0 and
      arg.getExpr() = str and
      str.getValue() = "echo" or str.getValue() = "cat" or str.getValue() = "ls" or str.getValue() = "rm" or str.getValue() = "mv" or str.getValue() = "cp" or str.getValue() = "wget" or str.getValue() = "curl" or str.getValue() = "chmod" or str.getValue() = "chown" or str.getValue() = "sudo" or str.getValue() = "su" or str.getValue() = "find" or str.getValue() = "grep" or str.getValue() = "sort" or str.getValue() = "uniq" or str.getValue() = "tr" or str.getValue() = "sed" or str.getValue() = "awk" or str.getValue() = "tar" or str.getValue() = "gzip" or str.getValue() = "bzip2" or str.getValue() = "zip" or str.getValue() = "unzip" or str.getValue() = "rsync" or str.getValue() = "scp" or str.getValue() = "ssh" or str.getValue() = "ftp" or str.getValue() = "telnet" or str.getValue() = "nc" or str.getValue() = "ncat" or str.getValue() = "ncat" or str.getValue() = "nc" or str.getValue() = "ping" or str.getValue() = "traceroute" or str.getValue() = "ping6" or str.getValue() = "traceroute6" or str.getValue() = "arp" or str.getValue() = "ifconfig" or str.getValue() = "ip" or str.getValue() = "route" or str.getValue() = "netstat" or str.getValue() = "ss" or str.getValue() = "iptables" or str.getValue() = "firewall-cmd" or str.getValue() = "systemctl" or str.getValue() = "journalctl" or str.getValue() = "dmesg" or str.getValue() = "ltrace" or str.getValue() = "strace" or str.getValue() = "gdb" or str.getValue() = "nm" or str.getValue() = "objdump" or str.getValue() = "readelf" or str.getValue() = "nm" or str.getValue() = "ld" or str.getValue() = "gcc" or str.getValue() = "make" or str.getValue() = "configure" or str.getValue() = "make" or str.getValue() = "install" or str.getValue() = "apt" or str.getValue() = "yum" or str.getValue() = "dnf" or str.getValue() = "pkg" or str.getValue() = "pacman" or str.getValue() = "zypper" or str.getValue() = "rpm" or str.getValue() = "dpkg" or str.getValue() = "apt-get" or str.getValue() = "apt-cache" or str.getValue() = "apt-key" or str.getValue() = "apt-config" or str.getValue() = "aptitude" or str.getValue() = "apt-rpm" or str.getValue() = "apt-ftparchive" or str.getValue() = "apt-secure" or str.getValue() = "apt-file" or str.getValue() = "apt-transport" or str.getValue() = "apt-transport-http" or str.getValue() = "apt-transport-https" or str.getValue() = "apt-transport-ftp" or str.getValue() = "apt-transport-tftp" or str.getValue() = "apt-transport-ncp" or str.getValue() = "apt-transport-s3" or str.getValue() = "apt-transport-union" or str.getValue() = "apt-transport-https" or str.getValue() = "apt-transport-ftp" or str.getValue() = "apt-transport-tftp" or str.getValue() = "apt-transport-ncp" or str.getValue() = "apt-transport-s3" or str.getValue() = "apt-transport-union" or str.getValue() = "apt-transport-https" or str.getValue() = "apt-transport-ftp" or str.getValue() = "apt-transport-tftp" or str.getValue() = "apt-transport-ncp" or str.getValue() = "apt-transport-s3" or str.getValue() = "apt-transport-union"
select call, "Potential command injection vulnerability via os.system with hardcoded command"