```ql
import python

from Call call, Argument arg, StringLiteral str
where 
  (call.getCallee() = "subprocess.run" or 
   call.getCallee() = "subprocess.call" or 
   call.getCallee() = "os.system" or 
   call.getCallee() = "subprocess.Popen") and
  arg.getArgumentPosition() = 0 and
  arg.getArgument() = str and
  str.getStringValue().contains("'$") or
  str.getStringValue().contains("`") or
  str.getStringValue().contains("&&") or
  str.getStringValue().contains(";") or
  str.getStringValue().contains("|") or
  str.getStringValue().contains("||") or
  str.getStringValue().contains(">>") or
  str.getStringValue().contains(">>>") or
  str.getStringValue().contains("<") or
  str.getStringValue().contains("<<") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )") or
  str.getStringValue().contains("$( )