/**
 * @name Weak KDF salt generation.
 * @description Detects key derivation functions that utilize salt values not generated by the approved random number generator (os.urandom).
 * @kind problem
 * @id py/kdf-weak-salt-gen
 * @problem.severity error
 * @precision high
 */

// Import core Python language analysis library
import python
// Import experimental cryptography concepts for security analysis
import experimental.cryptography.Concepts
// Import cryptography utilities with alias for helper functions
private import experimental.cryptography.utils.Utils as CryptoUtils

// Main query to identify KDF operations with insecure salt generation
from KeyDerivationOperation keyDerivationFunc, DataFlow::Node saltSource
where
  // Check if the KDF operation requires a salt parameter
  keyDerivationFunc.requiresSalt() and
  // Ensure the salt source is not from the approved os.urandom function
  not saltSource = API::moduleImport("os").getMember("urandom").getACall() and
  // Verify that the salt source is used as the salt configuration for this KDF
  saltSource = keyDerivationFunc.getSaltConfigSrc()
// Report the security issue with details about the weak salt source
select keyDerivationFunc, "Salt configuration is not from an accepted random source: $@. Must be os.urandom",
  saltSource, saltSource.toString()