/**
 * @name Weak KDF salt generation.
 * @description Detects key derivation functions (KDF) that use salt values 
 *              not generated by the approved random number generator (os.urandom).
 * @kind problem
 * @id py/kdf-weak-salt-gen
 * @problem.severity error
 * @precision high
 */

// Import standard Python analysis library
import python
// Import experimental cryptography concepts for cryptographic operations
import experimental.cryptography.Concepts
// Import utility functions for cryptographic analysis, aliased as Utils
private import experimental.cryptography.utils.Utils as Utils

// Identify key derivation operations and their salt sources
from KeyDerivationOperation keyDerivationOp, DataFlow::Node saltSource
where
  // Verify the operation requires a salt parameter
  keyDerivationOp.requiresSalt() and
  // Confirm the salt source is the configuration source for this operation
  saltSource = keyDerivationOp.getSaltConfigSrc() and
  // Ensure the salt is not generated by the approved os.urandom function
  not API::moduleImport("os").getMember("urandom").getACall() = saltSource
// Report the vulnerability with details about the weak salt source
select keyDerivationOp, "Salt configuration is not from an accepted random source: $@. Must be os.urandom",
  saltSource, saltSource.toString()