/**
 * @name Weak KDF salt generation
 * @description Identifies key derivation functions (KDF) that use salt values
 *              not generated by the approved random number generator (os.urandom).
 * @kind problem
 * @id py/kdf-weak-salt-gen
 * @problem.severity error
 * @precision high
 */

// Import standard Python analysis library
import python
// Import experimental cryptography concepts for cryptographic operations
import experimental.cryptography.Concepts
// Import utility functions for cryptographic analysis, aliased as Utils
private import experimental.cryptography.utils.Utils as Utils

// Identify key derivation operations and their salt sources
from KeyDerivationOperation kdfOp, DataFlow::Node saltOrigin
where
  // Validate operation requires salt parameter
  kdfOp.requiresSalt() and
  // Trace salt configuration source for the operation
  saltOrigin = kdfOp.getSaltConfigSrc() and
  // Ensure salt is not generated by approved os.urandom function
  not API::moduleImport("os").getMember("urandom").getACall() = saltOrigin
// Report vulnerability with details about weak salt source
select kdfOp, "Salt configuration is not from an accepted random source: $@. Must be os.urandom",
  saltOrigin, saltOrigin.toString()