/**
 * @name Weak block mode IV or nonce
 * @description Identifies insecure initialization vectors (IVs) or nonces in block cipher operations.
 *              Detects cases where IVs/nonces are either missing or not generated by os.urandom.
 *              Excludes Fernet as it handles IV generation internally. Complex cases may require
 *              manual verification.
 *
 * @id py/weak-block-mode-iv-or-nonce
 * @kind problem
 * @problem.severity error
 * @precision high
 * @tags security
 *       cryptography
 */

import python
import experimental.cryptography.Concepts

// Identify block cipher operations with vulnerable IV/nonce configurations
from BlockMode blockCipherOp, string warningMsg, DataFlow::Node vulnSource
where
  // Exclude Fernet (manages IV generation internally)
  not blockCipherOp instanceof CryptographyModule::Encryption::SymmetricEncryption::Fernet::CryptographyFernet and
  (
    // Check for missing IV/nonce OR non-os.urandom source
    not blockCipherOp.hasIVorNonce() or
    not API::moduleImport("os").getMember("urandom").getACall() = blockCipherOp.getIVorNonce()
  ) and
  // Determine vulnerability source based on IV/nonce presence
  (
    if not blockCipherOp.hasIVorNonce()
    then vulnSource = blockCipherOp  // Case 1: Missing IV/nonce
    else vulnSource = blockCipherOp.getIVorNonce()  // Case 2: Insecure IV/nonce source
  ) and
  // Standardize final alert message
  warningMsg = "Block mode is not using an accepted IV/Nonce initialization: $@"
select blockCipherOp, warningMsg, vulnSource, vulnSource.toString()