/**
 * @name Weak KDF salt generation
 * @description Detects when key derivation functions use salt values not generated by os.urandom
 * @kind problem
 * @id py/kdf-weak-salt-gen
 * @problem.severity error
 * @precision high
 */

// Import Python language support
import python
// Import cryptographic concepts for analysis
import experimental.cryptography.Concepts
// Import cryptographic utilities with alias
private import experimental.cryptography.utils.Utils as Utils

// Identify key derivation operations with weak salt generation
from KeyDerivationOperation kdfOperation, DataFlow::Node saltSource
where
  // Verify the KDF operation requires salt and identify its source
  kdfOperation.requiresSalt() and
  saltSource = kdfOperation.getSaltConfigSrc() and
  // Ensure the salt source is not generated by os.urandom
  not API::moduleImport("os").getMember("urandom").getACall() = saltSource
// Report KDF operations with weak salt generation
select kdfOperation, "Salt configuration is not from an accepted random source: $@. Must be os.urandom",
  saltSource, saltSource.toString()