/**
 * @name Insecure KDF Salt Generation
 * @description Identifies key derivation functions that use salt values not generated by the approved random number generator (os.urandom).
 * @kind problem
 * @id py/kdf-weak-salt-gen
 * @problem.severity error
 * @precision high
 */

// Import core Python language analysis library
import python
// Import experimental cryptography concepts for security analysis
import experimental.cryptography.Concepts
// Import cryptography utilities with alias for helper functions
private import experimental.cryptography.utils.Utils as CryptoUtils

// Main query to identify KDF operations with insecure salt generation
from KeyDerivationOperation kdfOperation, DataFlow::Node saltOrigin
where
  // Condition 1: The KDF operation requires a salt parameter
  kdfOperation.requiresSalt() and
  // Condition 2: The salt source is not from the approved os.urandom function
  not saltOrigin = API::moduleImport("os").getMember("urandom").getACall() and
  // Condition 3: The salt source is used as the salt configuration for this KDF
  saltOrigin = kdfOperation.getSaltConfigSrc()
// Report the security issue with details about the weak salt source
select kdfOperation, "Salt configuration is not from an accepted random source: $@. Must be os.urandom",
  saltOrigin, saltOrigin.toString()