/**
 * @name Weak KDF salt generation.
 * @description KDF salts must be generated by an approved random number generator (os.urandom)
 * @kind problem
 * @id py/kdf-weak-salt-gen
 * @problem.severity error
 * @precision high
 */

// 导入Python库
import python
// 导入实验性加密概念库
import experimental.cryptography.Concepts
// 私有导入实验性加密工具库，并重命名为Utils
private import experimental.cryptography.utils.Utils as Utils

// 从KeyDerivationOperation操作和DataFlow::Node盐源中选择数据流节点
from KeyDerivationOperation op, DataFlow::Node saltSrc
// 条件：操作需要盐并且盐源不是来自os.urandom的调用，且盐源是操作的盐配置源
where
  op.requiresSalt() and // 检查操作是否需要盐
  not API::moduleImport("os").getMember("urandom").getACall() = saltSrc and // 检查盐源是否不是来自os.urandom的调用
  saltSrc = op.getSaltConfigSrc() // 检查盐源是否是操作的盐配置源
// 选择操作和相关信息，报告问题
select op, "Salt configuration is not from an accepted random source: $@. Must be os.urandom",
  saltSrc, saltSrc.toString()
