/**
 * @name Weak block mode IV or nonce
 * @description Identifies cryptographic operations using block modes with weak, obsolete, or otherwise
 *              unacceptable initialization vectors (IVs) or nonces. Specifically targets cases where
 *              IVs or nonces are not generated by a cryptographically secure random number generator.
 *
 *            NOTE: For analysis simplicity, any IV or nonce that cannot be verified as originating
 *                  from os.urandom is flagged. More nuanced considerations, such as proper nonce usage
 *                  in specific modes, are not currently handled. For example, GCM mode requires a
 *                  nonce; while using urandom is acceptable, incorrect configuration is still possible.
 *                  We assume GCM mode issues are caught by a separate query and require crypto board review.
 *
 *                  Additionally, functions that infer both mode and IV may be flagged by this query.
 *                  Currently, we rely on users suppressing these cases rather than filtering them out.
 *                  Fernet is explicitly excluded as its implementation properly uses os.urandom.
 * @id py/weak-block-mode-iv-or-nonce
 * @kind problem
 * @problem.severity error
 * @precision high
 */

import python
import experimental.cryptography.Concepts

// Select block mode operations, error messages, and related configuration nodes
from BlockMode blockModeOperation, string errorMessage, DataFlow::Node configurationNode
where
  // Exclude Fernet encryption module instances as they use os.urandom internally
  not blockModeOperation instanceof CryptographyModule::Encryption::SymmetricEncryption::Fernet::CryptographyFernet and
  (
    // Check if the operation lacks an IV/Nonce or uses one not generated by os.urandom
    not blockModeOperation.hasIVorNonce() or
    not API::moduleImport("os").getMember("urandom").getACall() = blockModeOperation.getIVorNonce()
  ) and
  (
    // Set appropriate message and configuration node based on IV/Nonce presence
    if not blockModeOperation.hasIVorNonce()
    then (
      configurationNode = blockModeOperation and 
      errorMessage = "Block mode is missing IV/Nonce initialization."
    )
    else (
      configurationNode = blockModeOperation.getIVorNonce()
    )
  ) and
  // Finalize error message with specific details about the unacceptable initialization
  errorMessage = "Block mode is not using an accepted IV/Nonce initialization: $@"
select blockModeOperation, errorMessage, configurationNode, configurationNode.toString()