/**
 * @name Weak block mode IV or nonce
 * @description Identifies weak initialization vectors (IVs) or nonces in block cipher operations.
 *              This query flags cases where IVs/nonces are either missing or not generated by os.urandom.
 *              Fernet is excluded as it handles IV generation internally. Complex cases may require
 *              manual review.
 *
 * @id py/weak-block-mode-iv-or-nonce
 * @kind problem
 * @problem.severity error
 * @precision high
 * @tags security
 *       cryptography
 */

import python
import experimental.cryptography.Concepts

// Identify block mode operations with weak IV/nonce configurations
from BlockMode blockModeOp, string errorMsg, DataFlow::Node weakSource
where
  // Exclude Fernet (handles IV generation internally)
  not blockModeOp instanceof CryptographyModule::Encryption::SymmetricEncryption::Fernet::CryptographyFernet and
  (
    // Check for missing IV/nonce OR non-os.urandom source
    not blockModeOp.hasIVorNonce() or
    not API::moduleImport("os").getMember("urandom").getACall() = blockModeOp.getIVorNonce()
  ) and
  // Determine the source node and temporary error message based on IV/nonce presence
  (
    // Case 1: Missing IV/nonce
    if not blockModeOp.hasIVorNonce()
    then (
      weakSource = blockModeOp and 
      errorMsg = "Block mode is missing IV/Nonce initialization."
    )
    // Case 2: IV/nonce from insecure source
    else (
      weakSource = blockModeOp.getIVorNonce()
    )
  ) and
  // Set the final error message
  errorMsg = "Block mode is not using an accepted IV/Nonce initialization: $@"
select blockModeOp, errorMsg, weakSource, weakSource.toString()