/**
 * @name Weak KDF salt generation
 * @description Detects when key derivation functions use salt values not generated by os.urandom
 * @kind problem
 * @id py/kdf-weak-salt-gen
 * @problem.severity error
 * @precision high
 */

// Import Python language support
import python
// Import cryptographic concepts for analysis
import experimental.cryptography.Concepts
// Import cryptographic utilities with alias
private import experimental.cryptography.utils.Utils as Utils

// 查找所有密钥派生操作及其盐值来源
from KeyDerivationOperation keyDerivationOp, DataFlow::Node saltOrigin
where
  // 确保密钥派生操作需要盐值
  keyDerivationOp.requiresSalt() and
  // 确保盐值来源是密钥派生操作的盐配置源
  saltOrigin = keyDerivationOp.getSaltConfigSrc() and
  // 检查盐值是否来自os.urandom
  not API::moduleImport("os").getMember("urandom").getACall() = saltOrigin
// 选择密钥派生操作，报告弱盐生成问题
select keyDerivationOp, "Salt configuration is not from an accepted random source: $@. Must be os.urandom",
  saltOrigin, saltOrigin.toString()