/**
 * @name Weak Key Derivation Function Salt Generation
 * @description Identifies key derivation functions (KDF) utilizing salt values
 *              not generated by the approved cryptographic random number generator (os.urandom).
 * @kind problem
 * @id py/kdf-weak-salt-gen
 * @problem.severity error
 * @precision high
 */

// Import standard Python analysis library
import python
// Import experimental cryptography concepts for cryptographic operations
import experimental.cryptography.Concepts
// Import utility functions for cryptographic analysis, aliased as Utils
private import experimental.cryptography.utils.Utils as Utils

// Identify key derivation operations and their salt origins
from KeyDerivationOperation kdfOperation, DataFlow::Node saltOrigin
where
  // Verify operation requires salt parameter
  kdfOperation.requiresSalt() and
  // Confirm salt origin matches the operation's configuration source
  saltOrigin = kdfOperation.getSaltConfigSrc() and
  // Ensure salt is not generated by approved os.urandom function
  not API::moduleImport("os").getMember("urandom").getACall() = saltOrigin
// Report vulnerability with details about the weak salt source
select kdfOperation, "Salt configuration is not from an accepted random source: $@. Must be os.urandom",
  saltOrigin, saltOrigin.toString()