/**
 * @name Weak block mode IV or nonce
 * @description Identifies weak initialization vectors (IVs) or nonces in block cipher operations.
 *              Flags cases where IVs/nonces are missing or not generated by os.urandom.
 *              Excludes Fernet (handled internally) and requires manual review for complex cases.
 *
 *            NOTE: This simplified query flags any IV/nonce not from os.urandom or undetermined origin.
 *                  Nuanced patterns (e.g., GCM nonce usage) require expert review. Functions inferring
 *                  both mode and IV may trigger false positives (handled via suppression). Fernet is
 *                  explicitly excluded due to internal os.urandom usage.
 * @id py/weak-block-mode-iv-or-nonce
 * @kind problem
 * @problem.severity error
 * @precision high
 */

import python
import experimental.cryptography.Concepts

// Identify block cipher operations with weak IV/nonce configurations
from BlockMode cipherOperation, string alertMessage, DataFlow::Node originNode
where
  // Exclude Fernet (handles IV generation internally)
  not cipherOperation instanceof CryptographyModule::Encryption::SymmetricEncryption::Fernet::CryptographyFernet and
  (
    // Detect missing IV/nonce OR non-os.urandom source
    not cipherOperation.hasIVorNonce() or
    not API::moduleImport("os").getMember("urandom").getACall() = cipherOperation.getIVorNonce()
  ) and
  // Configure alert details based on IV/nonce presence
  (
    // Case 1: Missing IV/nonce
    if not cipherOperation.hasIVorNonce()
    then (
      originNode = cipherOperation and 
      alertMessage = "Block mode is missing IV/Nonce initialization: $@"
    )
    // Case 2: IV/nonce from insecure source
    else (
      originNode = cipherOperation.getIVorNonce() and
      alertMessage = "Block mode is not using an accepted IV/Nonce initialization: $@"
    )
  )
select cipherOperation, alertMessage, originNode, originNode.toString()