/**
 * @name Weak block mode IV or nonce
 * @description Detects cryptographic operations using block modes with weak, obsolete, or otherwise
 *              unacceptable initialization vectors (IVs) or nonces. Specifically targets cases where
 *              IVs or nonces are not generated by a cryptographically secure random number generator.
 *
 *            NOTE: For analysis simplicity, any IV or nonce that cannot be verified as originating
 *                  from os.urandom is flagged. More nuanced considerations, such as proper nonce usage
 *                  in specific modes, are not currently handled. For example, GCM mode requires a
 *                  nonce; while using urandom is acceptable, incorrect configuration is still possible.
 *                  We assume GCM mode issues are caught by a separate query and require crypto board review.
 *
 *                  Additionally, functions that infer both mode and IV may be flagged by this query.
 *                  Currently, we rely on users suppressing these cases rather than filtering them out.
 *                  Fernet is explicitly excluded as its implementation properly uses os.urandom.
 * @id py/weak-block-mode-iv-or-nonce
 * @kind problem
 * @problem.severity error
 * @precision high
 */

import python
import experimental.cryptography.Concepts

// Identify block mode operations with weak IV/nonce initialization
from BlockMode cryptoOperation, string diagnosticMessage, DataFlow::Node problematicNode
where
  // Exclude Fernet as it properly uses os.urandom internally
  not cryptoOperation instanceof CryptographyModule::Encryption::SymmetricEncryption::Fernet::CryptographyFernet and
  (
    // Check for missing IV/nonce or non-os.urandom source
    not cryptoOperation.hasIVorNonce() or
    not API::moduleImport("os").getMember("urandom").getACall() = cryptoOperation.getIVorNonce()
  ) and
  // Determine the problematic node based on IV/nonce presence
  (
    if not cryptoOperation.hasIVorNonce()
    then problematicNode = cryptoOperation  // Operation itself is problematic
    else problematicNode = cryptoOperation.getIVorNonce()  // IV/nonce source is problematic
  ) and
  // Set unified diagnostic message
  diagnosticMessage = "Block mode is not using an accepted IV/Nonce initialization: $@"
select cryptoOperation, diagnosticMessage, problematicNode, problematicNode.toString()