/**
 * @name Insecure KDF Salt Generation
 * @description Detects key derivation functions using salt values not generated by the approved random number generator (os.urandom).
 * @kind problem
 * @id py/kdf-weak-salt-gen
 * @problem.severity error
 * @precision high
 */

// Import core Python language analysis library
import python
// Import experimental cryptography concepts for security analysis
import experimental.cryptography.Concepts
// Import cryptography utilities with alias for helper functions
private import experimental.cryptography.utils.Utils as CryptoUtils

// Identify KDF operations with insecure salt generation
from KeyDerivationOperation kdfOp, DataFlow::Node saltSource
where
  // The KDF operation requires a salt parameter
  kdfOp.requiresSalt() and
  // The salt source is used as the salt configuration for this KDF
  saltSource = kdfOp.getSaltConfigSrc() and
  // The salt source is not from the approved os.urandom function
  not saltSource = API::moduleImport("os").getMember("urandom").getACall()
// Report the security issue with details about the weak salt source
select kdfOp, "Salt configuration is not from an accepted random source: $@. Must be os.urandom",
  saltSource, saltSource.toString()