/**
 * @name Weak KDF salt generation.
 * @description Identifies instances where key derivation functions (KDFs) use salt values
 *              that are not generated by the approved cryptographically secure random
 *              number generator (os.urandom). Using predictable or weak salts can
 *              compromise the security of the derived keys.
 * @kind problem
 * @id py/kdf-weak-salt-gen
 * @problem.severity error
 * @precision high
 */

// Import Python language library
import python
// Import experimental cryptography concepts library
import experimental.cryptography.Concepts
// Private import of experimental cryptography utilities, aliased as CryptoUtils
private import experimental.cryptography.utils.Utils as CryptoUtils

// Select data flow nodes from key derivation operations and salt sources
from KeyDerivationOperation keyDerivationOp, DataFlow::Node saltOrigin
where
  // Check if the key derivation operation requires a salt
  keyDerivationOp.requiresSalt() and
  // Verify that the salt source is not from os.urandom call
  not API::moduleImport("os").getMember("urandom").getACall() = saltOrigin and
  // Confirm that the salt source is the salt configuration for the operation
  saltOrigin = keyDerivationOp.getSaltConfigSrc()
// Select the operation and related information for reporting the issue
select keyDerivationOp, "Salt configuration is not from an accepted random source: $@. Must be os.urandom",
  saltOrigin, saltOrigin.toString()