/**
 * @name Weak KDF salt generation.
 * @description KDF salts must be generated by an approved random number generator (os.urandom)
 * @kind problem
 * @id py/kdf-weak-salt-gen
 * @problem.severity error
 * @precision high
 */

// 导入Python库
import python
// 导入实验性加密概念库
import experimental.cryptography.Concepts
// 私有导入实验性加密工具库，并重命名为Utils
private import experimental.cryptography.utils.Utils as Utils

// 查找密钥派生操作及其盐源
from KeyDerivationOperation kdfOperation, DataFlow::Node saltSource
where
  // 检查密钥派生操作是否需要盐值
  kdfOperation.requiresSalt() and
  // 检查盐源是否来自os.urandom的调用
  not API::moduleImport("os").getMember("urandom").getACall() = saltSource and
  // 确认盐源是密钥派生操作的盐配置源
  saltSource = kdfOperation.getSaltConfigSrc()
// 选择密钥派生操作，报告弱盐生成问题
select kdfOperation, "Salt configuration is not from an accepted random source: $@. Must be os.urandom",
  saltSource, saltSource.toString()