/**
 * @name Weak KDF salt generation.
 * @description Identifies key derivation functions (KDF) that use salt values not generated by the approved random number generator (os.urandom).
 * @kind problem
 * @id py/kdf-weak-salt-gen
 * @problem.severity error
 * @precision high
 */

// Import standard Python language library
import python
// Import experimental cryptography concepts for security analysis
import experimental.cryptography.Concepts
// Import and alias cryptography utilities for helper functions
private import experimental.cryptography.utils.Utils as Utils

// Identify KDF operations with insecure salt generation
from KeyDerivationOperation kdfOperation, DataFlow::Node saltOrigin
where
  // Verify the KDF operation requires salt parameter
  kdfOperation.requiresSalt() and
  // Ensure the salt source is not from the approved os.urandom function
  not saltOrigin = API::moduleImport("os").getMember("urandom").getACall() and
  // Confirm the salt source is used as the salt configuration for this KDF
  saltOrigin = kdfOperation.getSaltConfigSrc()
// Report the security issue with details about the weak salt source
select kdfOperation, "Salt configuration is not from an accepted random source: $@. Must be os.urandom",
  saltOrigin, saltOrigin.toString()