/**
 * @name Number of commits
 * @description Counts the number of commits in the repository, excluding artificial changes.
 *              Artificial changes are typically generated by tools and not by human developers.
 * @kind treemap
 * @id py/historical-number-of-commits
 * @treemap.warnOn highValues
 * @metricType commit
 * @metricAggregate sum
 */

// Import Python language support
import python
// Import version control system (VCS) functionality
import external.VCS

// Define source of commits: all commits in the repository
from Commit commitRecord
// Filter condition: exclude commits marked as artificial changes
where not artificialChange(commitRecord)
// Output revision identifier and unit count (1 per commit)
select commitRecord.getRevisionName(), 1